### ISSUE TITLE
Game Clear/Win Screen

### ISSUE THREAD

**Issue by JAlexHouse** [JAlexHouse/invertsquared#25]

**Comment by melindachhu** [comment]
what do you mean by this? are there additional elements to add?

**Comment by JAlexHouse** [comment]
well there’s still the note in the screen that says add the reset button, has that been fixed?

**Comment by melindachhu** [comment]
yes, it is on my branch, i can pull from dev and push

**Comment by JAlexHouse** [comment]
sounds good with me!
